import { AppShell } from "@/components/dashboard";

const screens = [
  ["Overview", "The latest persisted forecast, operational attention, source health, and briefing availability."],
  ["Forecasts", "Hourly demand outputs, peak timing, ramps, actuals where available, and persisted intervals when available."],
  ["Alerts", "Deterministic attention signals with persisted evidence and lifecycle history."],
  ["Data Quality", "Latest source-health checks, blocking state, and safe quality notes."],
  ["Scenarios", "Bounded simulations showing how weather or load assumptions change expected demand."],
  ["Briefing", "Structured deterministic facts drawn from persisted operational evidence."],
  ["Model Performance", "Persisted baseline, monitoring, and drift evidence without browser-calculated claims."],
  ["System Status", "Safe service and record-status visibility without infrastructure secrets."],
];

export default function AboutPage() {
  return <AppShell screen="about" demoMode={process.env.NEXT_PUBLIC_GRIDOPS_DEMO_MODE === "true"}><article className="about-page"><header className="page-heading"><div><p className="eyebrow">About the product</p><h1>How GridOps Intelligence works</h1><p>An evidence-backed view of Ontario electricity demand operations and planning context.</p></div></header><AboutSection title="What GridOps Intelligence does"><p>GridOps Intelligence organizes electricity-demand and weather data, validates inputs, produces day-ahead demand forecasts, tracks model performance, detects attention conditions, and supports controlled planning scenarios.</p></AboutSection><AboutSection title="The problem it addresses"><p>Electricity-demand analysis often requires combining separate demand, weather, data-quality, forecast, and operational signals. GridOps brings those signals together into one evidence-backed interface.</p></AboutSection><AboutSection title="How it works"><ol className="how-it-works"><li><strong>Data ingestion</strong><span>Demand and weather records are collected and preserved with retrieval and source metadata.</span></li><li><strong>Data quality</strong><span>Completeness, freshness, continuity, duplicates, ranges, and source health are checked.</span></li><li><strong>Forecasting</strong><span>Historical demand, calendar effects, and weather features are used to generate a 24-hour demand forecast.</span></li><li><strong>Monitoring</strong><span>Forecast performance, model drift, peak demand, and ramp behavior are tracked.</span></li><li><strong>Decision support</strong><span>Alerts, planning scenarios, and deterministic briefing facts are created from persisted evidence.</span></li><li><strong>Dashboard</strong><span>Forecasts, alerts, quality views, scenarios, and model evidence are presented in one operational interface.</span></li></ol></AboutSection><AboutSection title="What each screen shows"><div className="screen-explanation-grid">{screens.map(([name, description]) => <section key={name}><h3>{name}</h3><p>{description}</p></section>)}</div></AboutSection><AboutSection title="Demo mode"><p>Fixture-backed demonstration data may be synthetic or seeded and is not live IESO data. Scenarios are simulations, some prediction intervals may be unavailable, and the dashboard does not control the electricity grid.</p></AboutSection><AboutSection title="Who this is for"><p>Energy analysts, data engineers, forecasting analysts, operations analysts, planning analysts, ML engineers, and infrastructure analytics teams can use this project to explore an evidence-oriented demand workflow.</p></AboutSection><AboutSection title="What the project demonstrates"><p>Data engineering, PostgreSQL data modeling, FastAPI services, data-quality systems, time-series forecasting, model monitoring, decision-support logic, Next.js dashboard development, testing, and container deployment.</p></AboutSection></article></AppShell>;
}

function AboutSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="about-section"><h2>{title}</h2>{children}</section>; }
