"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

import { AppShell, formatOntarioTime } from "@/components/dashboard";
import { ApiClientError, GridOpsApiClient } from "@/lib/api-client";
import { fixtureAlertDetail, fixtureAlerts, fixtureBriefing, fixtureDemoData, fixtureScenario } from "@/lib/demo-data";
import type { AlertDetail, AlertSummary, BriefingResponse, ScenarioCreatePayload, ScenarioResponse } from "@/lib/contracts";

const demoFallback = process.env.NEXT_PUBLIC_GRIDOPS_USE_DEMO_DATA === "true";
const demoMode = process.env.NEXT_PUBLIC_GRIDOPS_DEMO_MODE === "true";

export function PageHeading({ title, context, fixture }: { title: string; context: string; fixture?: boolean }) {
  return <header className="page-heading"><div><p className="eyebrow">Decision support</p><h1>{title}</h1><p>{context}</p></div>{fixture ? <span className="fixture-note">Fixture-backed demonstration data</span> : null}</header>;
}

function Loading() { return <section className="card loading-state" aria-live="polite"><h2>Loading persisted records</h2><p>Retrieving the selected decision-support evidence.</p></section>; }
function Failure({ error }: { error: ApiClientError }) { return <section className="card unavailable-state" role="alert"><h2>Decision-support data is unavailable</h2><p>{error.kind === "timeout" ? "The backend did not respond before the dashboard timeout." : error.message}</p><p>Enable the explicit fixture-backed demo fallback for a local demonstration.</p></section>; }

export function AlertsPage() {
  const [alerts, setAlerts] = useState<AlertSummary[] | null>(null); const [fixture, setFixture] = useState(false); const [error, setError] = useState<ApiClientError | null>(null);
  useEffect(() => { new GridOpsApiClient().getAlerts().then(setAlerts).catch((reason: unknown) => { if (demoFallback) { setAlerts(fixtureAlerts); setFixture(true); } else setError(reason instanceof ApiClientError ? reason : new ApiClientError("The alerts could not be loaded.", "network")); }); }, []);
  const active = alerts?.filter((alert) => ["open", "acknowledged"].includes(alert.state)) ?? [];
  return <AppShell screen="alerts" demoMode={demoMode}><PageHeading title="Alerts" context="Persisted deterministic attention signals; not official IESO emergency or reliability categories." fixture={fixture} />{error ? <Failure error={error} /> : !alerts ? <Loading /> : <><section className="card card-wide"><p className="eyebrow">Current attention</p><h2>{active.length} active alert{active.length === 1 ? "" : "s"}</h2><p>All persisted alerts are shown below. No alert evaluation or lifecycle controls are exposed here.</p></section>{alerts.length === 0 ? <section className="card empty-state"><h2>No alerts are available</h2><p>No persisted alert records are available for this view.</p></section> : <div className="alert-grid">{alerts.map((alert) => <article className="card" key={alert.alert_id}><div className="card-header"><div><p className="eyebrow">{alert.alert_type.replaceAll("_", " ")}</p><h2>{alert.title}</h2></div><span className={`status-badge status-${alert.severity}`}>{alert.severity}</span></div><p><strong>Lifecycle:</strong> {alert.state.replaceAll("_", " ")}</p><p><strong>Target:</strong> {alert.target_interval_start_utc ? formatOntarioTime(alert.target_interval_start_utc) : "Not recorded"}</p><p><strong>Evidence:</strong> {alert.explanation}</p><p><strong>Threshold / context:</strong> {evidenceText(alert.current_evidence)}</p><Link href={`/alerts/${alert.alert_id}`}>View persisted evidence and history</Link></article>)}</div>}</>}</AppShell>;
}

export function AlertDetailPage({ alertId }: { alertId: number }) {
  const [alert, setAlert] = useState<AlertDetail | null>(null); const [fixture, setFixture] = useState(false); const [error, setError] = useState<ApiClientError | null>(null);
  useEffect(() => { new GridOpsApiClient().getAlert(alertId).then(setAlert).catch((reason: unknown) => { if (demoFallback && alertId === fixtureAlertDetail.alert_id) { setAlert(fixtureAlertDetail); setFixture(true); } else setError(reason instanceof ApiClientError ? reason : new ApiClientError("The alert could not be loaded.", "network")); }); }, [alertId]);
  return <AppShell screen="alerts" demoMode={demoMode}><PageHeading title={alert ? `Alert #${alert.alert_id}` : "Alert detail"} context="Immutable persisted evidence and lifecycle history." fixture={fixture} />{error ? <Failure error={error} /> : !alert ? <Loading /> : <div className="screen-grid"><section className="card card-wide"><div className="card-header"><div><p className="eyebrow">{alert.alert_type.replaceAll("_", " ")}</p><h2>{alert.title}</h2></div><span className={`status-badge status-${alert.severity}`}>{alert.severity} · {alert.state}</span></div><dl className="metric-grid"><Datum label="Target interval" value={alert.target_interval_start_utc ? formatOntarioTime(alert.target_interval_start_utc) : "Not recorded"} /><Datum label="Forecast run" value={alert.production_forecast_run_id ? `#${alert.production_forecast_run_id}` : "Not recorded"} /><Datum label="Opened" value={formatOntarioTime(alert.opened_at_utc)} /></dl><p className="notice">{alert.explanation}</p></section><EvidenceCard title="Current deterministic evidence" value={alert.current_evidence} /><section className="card"><p className="eyebrow">Limitations</p><h2>Evidence-bound interpretation</h2><p>Only persisted rule inputs and references are shown. This severity is not an official IESO category.</p></section><section className="card card-wide"><p className="eyebrow">Evidence history</p><h2>Immutable records</h2>{alert.evidence_records.length ? alert.evidence_records.map((item) => <div className="record" key={item.alert_evidence_id}><strong>{formatOntarioTime(item.generated_at_utc)}</strong><pre>{JSON.stringify(item.evidence, null, 2)}</pre></div>) : <p>No immutable evidence record is available.</p>}</section><section className="card card-wide"><p className="eyebrow">Lifecycle history</p><h2>Persisted transitions</h2>{alert.lifecycle_history.length ? <ul className="history-list">{alert.lifecycle_history.map((item) => <li key={item.lifecycle_history_id}><strong>{item.from_state ?? "created"} → {item.to_state}</strong> · {formatOntarioTime(item.changed_at_utc)}{item.transition_reason ? ` · ${item.transition_reason}` : ""}</li>)}</ul> : <p>No lifecycle transition is available.</p>}</section></div>}</AppShell>;
}

export function ScenariosPage() {
  const [forecastId, setForecastId] = useState<number | null>(null); const [result, setResult] = useState<ScenarioResponse | null>(null); const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false); const [fixture, setFixture] = useState(false);
  useEffect(() => { new GridOpsApiClient().getLatestForecast().then((forecast) => setForecastId(forecast?.forecast_run_id ?? null)).catch(() => { if (demoFallback) { setForecastId(fixtureDemoData.forecast?.forecast_run_id ?? null); setFixture(true); } }); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending || !forecastId) return; const values = new FormData(event.currentTarget); const parsed = validateScenario(values); if (typeof parsed === "string") { setMessage(parsed); return; } setMessage(null); setPending(true); try { const response = fixture ? fixtureScenario : await new GridOpsApiClient().createScenario({ production_forecast_run_id: forecastId, ...parsed }); setResult(response); } catch (error) { setMessage(error instanceof ApiClientError && error.status === 403 ? "This action is not available in the public demonstration." : "The scenario could not be created. Check the inputs and try again."); } finally { setPending(false); } }
  return <AppShell screen="scenarios" demoMode={demoMode}><PageHeading title="Scenarios" context="Bounded deterministic simulations, not forecasts or model recomputation." fixture={fixture} /><section className="card card-wide"><h2>Simulation inputs</h2><p>Public demo bounds: load growth −10 to +10%, added load −2,000 to +2,000 MW, temperature −10 to +10 C, humidity −30 to +30%. Server validation remains authoritative.</p>{forecastId === null ? <p className="notice">A persisted source forecast is required before a scenario can be submitted.</p> : <form className="scenario-form" onSubmit={submit}><label>Scenario type<select name="scenario_type" defaultValue="combined_weather_load"><option value="combined_weather_load">Combined weather and load</option><option value="demand_growth">Demand growth</option><option value="weather_adjustment">Weather adjustment</option></select></label><NumberField name="demand_growth_percent" label="Load growth percent" min={-10} max={10} /><NumberField name="added_load_mw" label="Added load MW" min={-2000} max={2000} /><NumberField name="temperature_delta_c" label="Temperature delta C" min={-10} max={10} /><NumberField name="humidity_delta_percent" label="Humidity delta percent" min={-30} max={30} /><button type="submit" disabled={pending}>{pending ? "Running simulation…" : "Run simulation"}</button>{message ? <p role="alert" className="form-error">{message}</p> : null}</form>}</section>{result ? <ScenarioResult result={result} /> : null}</AppShell>;
}

export function BriefingPage() {
  const [briefing, setBriefing] = useState<BriefingResponse | null | undefined>(undefined); const [fixture, setFixture] = useState(false); const [error, setError] = useState<ApiClientError | null>(null);
  useEffect(() => { new GridOpsApiClient().getLatestBriefing().then(setBriefing).catch((reason: unknown) => { if (demoFallback) { setBriefing(fixtureBriefing); setFixture(true); } else setError(reason instanceof ApiClientError ? reason : new ApiClientError("The briefing could not be loaded.", "network")); }); }, []);
  return <AppShell screen="briefing" demoMode={demoMode}><PageHeading title="Briefing" context="Persisted deterministic briefing facts only; no generated narrative." fixture={fixture} />{error ? <Failure error={error} /> : briefing === undefined ? <Loading /> : briefing === null ? <section className="card empty-state"><h2>No persisted briefing is available</h2><p>This public view does not generate a briefing.</p></section> : <section className="card card-wide"><div className="card-header"><div><p className="eyebrow">Briefing #{briefing.briefing_id}</p><h2>Generated {formatOntarioTime(briefing.generated_at_utc)}</h2></div><span className="status-badge">{briefing.status}</span></div><p>Source forecast run: #{briefing.production_forecast_run_id}</p><div className="briefing-facts">{briefing.facts.map((fact, index) => <article className="record" key={`${fact.fact_type}-${index}`}><h3>{fact.fact_type.replaceAll("_", " ")}</h3><pre>{JSON.stringify(fact.fact_value, null, 2)}</pre><p><strong>Evidence reference:</strong> {evidenceText(fact.evidence)}</p></article>)}</div><p className="notice">Confidence and uncertainty are limited to persisted facts. This screen does not infer or generate narrative.</p></section>}</AppShell>;
}

export function ScenarioResult({ result }: { result: ScenarioResponse }) { const row = result.result_rows[0]; return <><section className="card card-wide scenario-result" aria-live="polite"><p className="eyebrow">Simulation result #{result.scenario_id}</p><h2>{result.scenario_type.replaceAll("_", " ")}</h2><dl className="metric-grid"><Datum label="Source forecast run" value={`#${result.production_forecast_run_id}`} /><Datum label="Generated" value={formatOntarioTime(result.generated_at_utc)} /><Datum label="First interval delta" value={row ? `${row.delta_mw} MW` : "No interval rows"} /><Datum label="Peak change" value={stringValue(result.summary.peak_change_mw)} /><Datum label="Ramp change" value={stringValue(result.summary.largest_ramp_change_mw)} /></dl><p><strong>Assumptions:</strong> {result.assumptions.map((item) => `${item.assumption_name}: ${item.assumption_value ?? "recorded"} ${item.assumption_unit ?? ""}`).join("; ") || "None recorded"}</p><p className="notice">Scenario results are simulations, not official forecasts. Weather scenarios use a deterministic approximation; humidity assumptions may be stored without affecting values.</p><EvidenceCard title="Persisted limitations" value={result.limitations} /></section><ScenarioIntervalComparison result={result} /></>; }
function ScenarioIntervalComparison({ result }: { result: ScenarioResponse }) { return <section className="card card-wide"><p className="eyebrow">Interval comparison</p><h2>Persisted base and simulation values</h2>{result.result_rows.length ? <div className="table-scroll"><table><thead><tr><th>Ontario interval</th><th>Base forecast</th><th>Simulation</th><th>Delta</th></tr></thead><tbody>{result.result_rows.map((row) => <tr key={row.target_interval_start_utc}><td>{formatOntarioTime(row.target_interval_start_utc)}</td><td>{row.base_value_mw} MW</td><td>{row.scenario_value_mw} MW</td><td>{row.delta_mw} MW</td></tr>)}</tbody></table></div> : <p>No persisted scenario intervals are available.</p>}</section>; }
function EvidenceCard({ title, value }: { title: string; value: Record<string, unknown> }) { return <section className="card"><p className="eyebrow">Evidence</p><h2>{title}</h2><pre>{JSON.stringify(value, null, 2)}</pre></section>; }
function Datum({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function NumberField({ name, label, min, max }: { name: string; label: string; min: number; max: number }) { return <label>{label}<input name={name} type="number" min={min} max={max} step="any" aria-describedby={`${name}-help`} /><small id={`${name}-help`}>{min} to {max}</small></label>; }
export function validateScenario(values: FormData): Omit<ScenarioCreatePayload, "production_forecast_run_id"> | string { const fields: Array<[keyof ScenarioCreatePayload, number, number]> = [["demand_growth_percent", -10, 10], ["added_load_mw", -2000, 2000], ["temperature_delta_c", -10, 10], ["humidity_delta_percent", -30, 30]]; const output: Record<string, string> = { scenario_type: String(values.get("scenario_type")) }; for (const [name, min, max] of fields) { const raw = String(values.get(name) ?? "").trim(); if (!raw) continue; const value = Number(raw); if (!Number.isFinite(value)) return `${name.replaceAll("_", " ")} must be a finite number.`; if (value < min || value > max) return `${name.replaceAll("_", " ")} must be between ${min} and ${max}.`; output[name] = raw; } return output as Omit<ScenarioCreatePayload, "production_forecast_run_id">; }
function evidenceText(value: Record<string, unknown>) { return Object.entries(value).map(([key, item]) => `${key.replaceAll("_", " ")}: ${stringValue(item)}`).join("; ") || "No persisted evidence summary."; }
function stringValue(value: unknown) { return value === undefined || value === null ? "Not recorded" : String(value); }
