"""Forecasting foundations for GridOps Intelligence."""

from gridops.forecasting.artifacts import (
    ARTIFACT_DIR_ENV_VAR,
    DEFAULT_ARTIFACT_DIR,
    SavedArtifact,
    compute_artifact_hash,
    load_artifact,
    persist_model_artifact_metadata,
    resolve_artifact_dir,
    save_artifact,
)
from gridops.forecasting.candidate_models import (
    FEATURE_NAMES,
    TARGET_LIKE_FEATURE_NAMES,
    feature_vector_from_payload,
    make_gradient_boosting_candidate,
    payload_uses_no_target_actuals,
)
from gridops.forecasting.forecast_outputs import (
    PREDICTION_TYPE_P50_ONLY,
    ForecastGenerationConfig,
    ForecastGenerationResult,
    generate_forecast_from_selected_artifact,
)
from gridops.forecasting.horizons import ForecastHorizonTarget, generate_hourly_horizon
from gridops.forecasting.issue_contract import (
    DEFAULT_FORECAST_TYPE,
    DEFAULT_FORECASTING_FEATURE_VERSION,
    DEFAULT_HORIZON_HOURS,
    POINT_IN_TIME_SAFETY_RULE,
    ForecastIssueContract,
)
from gridops.forecasting.model_contracts import (
    DriftSummaryContract,
    ForecastPredictionContract,
    ForecastRunStatus,
    ModelArtifactContract,
    ModelArtifactStatus,
    ModelSelectionContract,
    ModelSelectionStatus,
    ModelTrainingRunContract,
    ModelTrainingStatus,
    PeakOutputContract,
    PerformanceSummaryContract,
    RampOutputContract,
)
from gridops.forecasting.model_selection import (
    REQUIRED_LINEAGE_FIELDS,
    SelectionGateDecision,
    evaluate_model_selection_gate,
    persist_model_selection_result,
)
from gridops.forecasting.training import (
    CandidateDatasetRow,
    CandidateTrainingConfig,
    CandidateTrainingResult,
    calculate_candidate_metrics,
    load_candidate_rows,
    load_selected_baseline_metrics,
    train_candidate_from_feature_snapshots,
)

__all__ = [
    "ARTIFACT_DIR_ENV_VAR",
    "DEFAULT_FORECASTING_FEATURE_VERSION",
    "DEFAULT_FORECAST_TYPE",
    "DEFAULT_HORIZON_HOURS",
    "DEFAULT_ARTIFACT_DIR",
    "FEATURE_NAMES",
    "POINT_IN_TIME_SAFETY_RULE",
    "PREDICTION_TYPE_P50_ONLY",
    "DriftSummaryContract",
    "ForecastHorizonTarget",
    "ForecastIssueContract",
    "ForecastGenerationConfig",
    "ForecastGenerationResult",
    "ForecastPredictionContract",
    "ForecastRunStatus",
    "ModelArtifactContract",
    "ModelArtifactStatus",
    "ModelSelectionContract",
    "ModelSelectionStatus",
    "ModelTrainingRunContract",
    "ModelTrainingStatus",
    "PeakOutputContract",
    "PerformanceSummaryContract",
    "REQUIRED_LINEAGE_FIELDS",
    "RampOutputContract",
    "SavedArtifact",
    "SelectionGateDecision",
    "TARGET_LIKE_FEATURE_NAMES",
    "CandidateDatasetRow",
    "CandidateTrainingConfig",
    "CandidateTrainingResult",
    "calculate_candidate_metrics",
    "compute_artifact_hash",
    "evaluate_model_selection_gate",
    "feature_vector_from_payload",
    "generate_hourly_horizon",
    "generate_forecast_from_selected_artifact",
    "load_artifact",
    "load_candidate_rows",
    "load_selected_baseline_metrics",
    "make_gradient_boosting_candidate",
    "payload_uses_no_target_actuals",
    "persist_model_artifact_metadata",
    "persist_model_selection_result",
    "resolve_artifact_dir",
    "save_artifact",
    "train_candidate_from_feature_snapshots",
]
